### ISSUE TITLE
node color is "NA" instead of NA

### ISSUE THREAD

**Issue by jokergoo** [talgalili/dendextend#10]
Hi Tal,

I am looking at the vignette and think the last part of the following example code `set("nodes_col", c("orange", "black", "plum", "NA"))` should better be `set("nodes_col", c("orange", "black", "plum", NA))`,
or else you will have a color with value `"NA"` instead of `NA`.

Zuguang

```{r}
dend <- iris[1:30,-5] %>% dist %>% hclust %>% as.dendrogram %>%
   set("branches_k_color", k=3) %>% set("branches_lwd", c(1.5,1,1.5)) %>%
   set("branches_lty", c(1,1,3,1,1,2)) %>%
   set("labels_colors") %>% set("labels_cex", c(.9,1.2)) %>% 
   set("nodes_pch", 19) %>% set("nodes_col", c("orange", "black", "plum", "NA"))


> attr(dend[[1]][[1]][[1]], "nodePar")
$lab.col
[1] "#CC476B"

$pch
[1] 19

$lab.cex
[1] 0.9

$col
[1] "NA"
```

**Comment by talgalili** [comment]
Thanks @jokergoo - it is now fixed. BTW, I just noticed you worked on:
https://github.com/jokergoo/ComplexHeatmap
https://github.com/jokergoo/EnrichedHeatmap
Do they work with dendrograms created by dendextend?

Cheers,
Tal

**Comment by jokergoo** [comment]
Yes, they all support dendrograms rendered by **dendextend** package. In the **ComplexHeatmap** vignette, there is also an example showing how to use **dendextend**.

**Comment by talgalili** [comment]
I see it here now: 
http://www.bioconductor.org/packages/release/bioc/vignettes/ComplexHeatmap/inst/doc/ComplexHeatmap.html

Cool :)
