### ISSUE TITLE
find_dendrogram function broken

### ISSUE THREAD

**Issue by jkh1** [talgalili/dendextend#102]
The find_dendrogram function appears broken. The example given in the doc returns just a single branch labelled '1'. See below.
I think the reason may be that the function uses unlist(dend) which returns a numeric vector and tries to match it to selected_labels which is a logical vector.
This is with R 4.0.2 and dendextend 1.13.4

```
# define dendrogram object to play with:
dend <- iris[, -5] %>%
  dist() %>%
  hclust() %>%
  as.dendrogram() %>%
  set("labels_to_character") %>%
  color_branches(k = 5)
first.subdend.only <- cutree(dend, 4) == 1
sub.dend <- find_dendrogram(dend, first.subdend.only)
# Plotting the result
par(mfrow = c(1, 2))
plot(dend, main = "Original dendrogram")
plot(sub.dend, main = "First subdendrogram")
```
results in 
![image](https://user-images.githubusercontent.com/5235745/90224860-9fcbd480-de10-11ea-86a4-19cdea0f1e22.png)

**Comment by talgalili** [comment]
Thanks for the bug report @jkh1 
The version on github (1.14.0) - now has a fixed version of the function. The documentation was fixed to now explain how the function can/should be used.
Please check and let me know if it doesn't what you want.

Cheers,
T

**Comment by jkh1** [comment]
Thanks @talgalili 
I think I have misunderstood what this function does. I thought it would be doing the same thing as ape::keep.tip().

**Comment by talgalili** [comment]
What does ape::keep.tip() do?
Is it similar to prune? (which emulates drop.tip)

**Comment by jkh1** [comment]
keep.tip gets the tree induced by the selected leaves so it is complementary to drop.tip/prune. One can work with prune, it's just that in my case it's simpler to work with what I need to keep than with what I need removed.

**Comment by talgalili** [comment]
Got it. Do you want to use prune to create a dendrogram version of
keep.tip? If so, please post it here and I'll add it to the package.
