### ISSUE TITLE
by_labels_branches_col using regexp

### ISSUE THREAD

**Issue by incivile** [talgalili/dendextend#11]
Hello,
at first I have to thank you for this great package! I have one suggestion about 'by_labels_branches_col' can you add option to look up branches using regexp? Some of my branches have category name in their labels and this would really help me.
Thank you again, great work!

**Comment by talgalili** [comment]
Hello @incivile , thank you for your kind words :)

If I understood your situation, probably the simplest way would be to find the labels you want to deal with upfront (using regex), and then supply them to the function. For example:

```
library(dendextend)

set.seed(23235)
ss <- sample(1:150, 10 )

# Getting the dend object
dend <- iris[ss,-5] %>% dist %>% hclust %>% as.dendrogram
dend %>% plot

the_labels <- labels(dend)[grepl("2", labels(dend))]
dend %>%
   set("by_labels_branches_col", the_labels) %>%
   plot
```

I am a bit hesitant about inserting that step inside the function.
If you have an example of why that would be better, please do share and I will re-consider.

Best,
Tal

**Comment by incivile** [comment]
Of course! I was so excited about this package, that I forgot the basics... :-)
Cheers!

**Comment by talgalili** [comment]
:+1:
