### ISSUE TITLE
using rect.dendrogram with as.ggdend

### ISSUE THREAD

**Issue by LSanselme** [talgalili/dendextend#13]
Hello,

Thanks for the quick fix of issue #12!
I have another issue related to `as.ggdend`: is there any way to use the `rect.dendrogram()` function within the ggplot paradigm? As `rect.dendogram` returns a list of k elements and not a dendrogram, it cannot be passed as parameter of `as.ggdend`.

Regards

**Comment by talgalili** [comment]
Hi @LSanselme ,
My pleasure.

Regarding your interesting request, I can think of how to create it (it is not currently possible).
Could you please explain how this would be more useful than just using it in base R graphs?
