### ISSUE TITLE
missing file link ‘cutree’

### ISSUE THREAD

**Issue by NahuelGrasso** [talgalili/dendextend#28]
Hello, 
I am trying to install this package in an R server (red hat) that doesn't have internet connection.
R version 3.2.1
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.6
I receive the following message:

Installing dendextend
'/usr/lib64/R/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/tmp/Rtmpp7T5VK/devtools222533ea0528/dendextend-master'  \
  --library='/usr/lib64/R/library' --install-tests

* installing *source* package ‘dendextend’ ...
** R
** data
*** moving datasets to lazyload DB
** demo
** inst
** tests
** preparing package for lazy loading
Warning: replacing previous import by ‘magrittr::%>%’ when loading ‘dendextend’
** help
*** installing help indices
  converting help for package ‘dendextend’
    finding HTML links ... done
    Bk                                      html
    Bk_permutations                         html
    Bk_plot                                 html
    DendSer.dendrogram                      html
    FM_index                                html
    FM_index_R                              html
    FM_index_permutation                    html
    FM_index_profdpm                        html
    all.equal.dendrogram                    html
    all_couple_rotations_at_k               html
    all_unique                              html
    as.dendlist                             html
    as.phylo.dendrogram                     html
    as_hclust_fixed                         html
    assign_dendextend_options               html
    assign_values_to_branches_edgePar       html
    assign_values_to_leaves_edgePar         html
    assign_values_to_leaves_nodePar         html
    assign_values_to_nodes_nodePar          html
    bakers_gamma_for_2_k_matrix             html
    branches_attr_by_clusters               html
    branches_attr_by_labels                 html
    circlize_dendrogram                     html
    click_rotate                            html
    collapse_branch                         html
    color_branches                          html
Rd warning: /tmp/Rtmpp7T5VK/devtools222533ea0528/dendextend-master/man/color_branches.Rd:58: missing file link ‘cutree’
Rd warning: /tmp/Rtmpp7T5VK/devtools222533ea0528/dendextend-master/man/color_branches.Rd:26: missing file link ‘cutree’
Rd warning: /tmp/Rtmpp7T5VK/devtools222533ea0528/dendextend-master/man/color_branches.Rd:28: missing file link ‘cutree’
Rd warning: /tmp/Rtmpp7T5VK/devtools222533ea0528/dendextend-master/man/color_branches.Rd:13: missing file link ‘cutree.dendrogram’
Rd warning: /tmp/Rtmpp7T5VK/devtools222533ea0528/dendextend-master/man/color_branches.Rd:193: missing file link ‘cutree’
    color_labels                            html
Rd warning: /tmp/Rtmpp7T5VK/devtools222533ea0528/dendextend-master/man/color_labels.Rd:44: missing file link ‘cutree’
Rd warning: /tmp/Rtmpp7T5VK/devtools222533ea0528/dendextend-master/man/color_labels.Rd:18: missing file link ‘cutree’
Rd warning: /tmp/Rtmpp7T5VK/devtools222533ea0528/dendextend-master/man/color_labels.Rd:20: missing file link ‘cutree’
Rd warning: /tmp/Rtmpp7T5VK/devtools222533ea0528/dendextend-master/man/color_labels.Rd:74: missing file link ‘cutree’
    color_unique_labels                     html
    colored_bars                            html
    common_subtrees_clusters                html
    cor.dendlist                            html
    cor_FM_index                            html
    cor_bakers_gamma                        html
Rd warning: /tmp/Rtmpp7T5VK/devtools222533ea0528/dendextend-master/man/cor_bakers_gamma.Rd:21: missing file link ‘cutree’
Rd warning: /tmp/Rtmpp7T5VK/devtools222533ea0528/dendextend-master/man/cor_bakers_gamma.Rd:35: missing file link ‘cutree’
    cor_common_nodes                        html
    cor_cophenetic                          html
    count_terminal_nodes                    html
    cut_lower_fun                           html
Rd warning: /tmp/Rtmpp7T5VK/devtools222533ea0528/dendextend-master/man/cut_lower_fun.Rd:31: missing file link ‘cutree.dendrogram’
Rd warning: /tmp/Rtmpp7T5VK/devtools222533ea0528/dendextend-master/man/cut_lower_fun.Rd:63: missing file link ‘cutree.dendrogram’
    cutree-methods                          html
    cutree_1h.dendrogram                    html
    cutree_1k.dendrogram                    html
    d3dendro_options                        html
    d3dendrogram                            html
    dend_diff                               html
    dendextend-package                      html
    dendextend_labels.dendrogram            html
Rd warning: /tmp/Rtmpp7T5VK/devtools222533ea0528/dendextend-master/man/dendextend_labels.dendrogram.Rd:18: missing file link ‘labels.dendrogram’
Rd warning: /tmp/Rtmpp7T5VK/devtools222533ea0528/dendextend-master/man/dendextend_labels.dendrogram.Rd:28: missing file link ‘labels.dendrogram’
    dendextend_options                      html
    dendlist                                html
    dist.dendlist                           html
    dist_long                               html
    distinct_edges                          html
    duplicate_leaf                          html
    entanglement                            html
    fac2num                                 html
    find_k                                  html
    fix_members_attr.dendrogram             html
    flatten.dendrogram                      html
    flip_leaves                             html
    get_branches_heights                    html
    get_childrens_heights                   html
    get_leaves_attr                         html
    get_leaves_branches_attr                html
    get_leaves_branches_col                 html
    get_leaves_edgePar                      html
    get_leaves_nodePar                      html
    get_nodes_attr                          html
    get_nodes_xy                            html
    get_root_branches_attr                  html
    ggdend                                  html
    hang.dendrogram                         html
    heights_per_k.dendrogram                html
    highlight_distinct_edges                html
    identify.dendrogram                     html
    intersect_trees                         html
    is.dendlist                             html
    is.dendrogram                           html
    is.dist                                 html
    is.hclust                               html
    is.natural.number                       html
    is.phylo                                html
    is_null_list                            html
    khan                                    html
    labels-assign                           html
    labels_cex                              html
    labels_colors                           html
Rd warning: /tmp/Rtmpp7T5VK/devtools222533ea0528/dendextend-master/man/labels_colors.Rd:67: missing file link ‘cutree’
    ladderize                               html
    leaf_Colors                             html
    lowest_common_branch                    html
    match_order_by_labels                   html
    match_order_dendrogram_by_old_order     html
    na_locf                                 html
    nleaves                                 html
    nnodes                                  html
    noded_with_condition                    html
    order.dendrogram-assign                 html
    order.hclust                            html
    partition_leaves                        html
    plot_horiz.dendrogram                   html
    prune                                   html
    prune_common_subtrees.dendlist          html
    prune_leaf                              html
    pvclust_show_signif                     html
    pvclust_show_signif_gradient            html
    raise.dendrogram                        html
    rank_branches                           html
    rank_order.dendrogram                   html
    rank_values_with_clusters               html
    rect.dendrogram                         html
    reexports                               html
Rd warning: /tmp/Rtmpp7T5VK/devtools222533ea0528/dendextend-master/man/reexports.Rd:13: missing file link ‘%>%’
    remove_branches_edgePar                 html
    remove_leaves_nodePar                   html
    remove_nodes_nodePar                    html
    rllply                                  html
    rotate                                  html
    rotate_DendSer                          html
    sample.dendrogram                       html
    seriate_dendrogram                      html
    set                                     html
    set_labels                              html
    shuffle                                 html
    sort_2_clusters_vectors                 html
    sort_dist_mat                           html
    sort_levels_values                      html
Rd warning: /tmp/Rtmpp7T5VK/devtools222533ea0528/dendextend-master/man/sort_levels_values.Rd:39: missing file link ‘cutree’
Rd warning: /tmp/Rtmpp7T5VK/devtools222533ea0528/dendextend-master/man/sort_levels_values.Rd:68: missing file link ‘cutree’
    tanglegram                              html
    theme_dendro                            html
    unbranch                                html
    unclass_dend                            html
    untangle                                html
    untangle_DendSer                        html
    untangle_random_search                  html
    untangle_step_rotate_1side              html
    untangle_step_rotate_2side              html
    which_leaf                              html
    which_node                              html
** building package indices
** installing vignettes
   ‘Cluster_Analysis.Rmd’
   ‘FAQ.Rmd’
   ‘Quick_Introduction.Rmd’
   ‘introduction.Rmd’
** testing if installed package can be loaded
Warning: replacing previous import by ‘magrittr::%>%’ when loading ‘dendextend’
* DONE (dendextend)
Making 'packages.html' ... done

I am worried about the messages:
- **missing file link ‘cutree’**
- **Warning: replacing previous import by ‘magrittr::%>%’ when loading ‘dendextend’**
- **missing file link ‘labels.dendrogram’**

I am having a problem using the library d3heatmap which needs this one and I dont know whether these errors are causing a bad installation of the d3heatmap or not.

If you have any advice please let me know
Thanks

**Comment by talgalili** [comment]
Hi there,
1) I believe your installation should be fine.
2) Please have a look at the [heatmaply ](https://cran.r-project.org/web/packages/heatmaply/) package (similar to d3heatmap, but with a bit more features).

With regards,
Tal

**Comment by NahuelGrasso** [comment]
Thanks, 
I already checked the heatmaply package, but it doesn't do what I want! 
For example: filter by row and column.
still wondering what i have wrong for the d3heatmap

**Comment by talgalili** [comment]
mmm, as far as I know (and I wrote the first package, and was also involved in writing d3heatmap) - both allow filter by rows and columns. You just need to click and drag, and you will get the relevant zoom.

With regards,
Tal

**Comment by NahuelGrasso** [comment]
Yes I know, but its simpler with d3heatmap to select rows and columns with a simple click. just a minimum issue there, however, I know d3heatmap doesn't include reactive events for the moment (great disadvantage)
I appreciate your help. I'll check for updates to the heatmaply package, If you want to include the functionallity I just mentioned, it would be awesome!

**Comment by talgalili** [comment]
heatmaply is based on plotly. I believe they are working on reactive events eventually, and believe they will get there.

Cheers,
Tal

**Comment by NahuelGrasso** [comment]
Perfect, I was also talking about the selection per row and column, and do something with the selection. 
Is there any chat in github? so we dont have to write on an issue

**Comment by talgalili** [comment]
First, the selection in plotly is by region. It does not recognize that area as a "row" or not. So what you want may not be easily done.
The crosstalk is experimented on here: 
https://github.com/rstudio/crosstalk

If you want the selection to go back to R, then you will probably need to use shiny (with a back-end shiny server), and I am not sure what could do it in the currently available technology. 

There may be a chat option here, but I'm not sure what it is (and also, I suspect I can't help more than what I wrote - sorry).
