### ISSUE TITLE
Is it possible to "mirror" a dendrogram?

### ISSUE THREAD

**Issue by EOneita** [talgalili/dendextend#29]
I have attached the image of the dendrogram I have created. Is there a code in ddextend that can be used to mirror this image? So, I would have the questions on the left, and the tree extending to the left, as an inverse of what is seen here.

I've been looking through the ddextend manual for code to this effect, but have struggled to find any. 

Thank you in advance for your help,
Elizabeth
<img width="948" alt="screen shot 2016-10-12 at 10 56 27" src="https://cloud.githubusercontent.com/assets/18596500/19296978/a27d3522-906a-11e6-8ef1-dd6570a389d0.png">

**Comment by talgalili** [comment]
Good question. The function you are looking for is `dendextend::plot_horiz.dendrogram`. This function is indeed not documented in the vignettes, although it is used by tanglegram. Here is an example for how to use it, I hope this helps:

```r
hc <- hclust(dist(USArrests), "ave")
d <- as.dendrogram(hc)
plot(d, horiz  = TRUE)

library(dendextend)
par(mar = c(3,7,1,1))
plot_horiz.dendrogram(d, side = TRUE)


```

Output

![image](https://cloud.githubusercontent.com/assets/976006/19301454/5588a80c-9068-11e6-9eda-7d5ba2c16bae.png)

With regards,
Tal

**Comment by EOneita** [comment]
Great, thank you so much! Worked like a charm.
