### ISSUE TITLE
Error when using as.ggdend() with type = "triangle"

### ISSUE THREAD

**Issue by kassambara** [talgalili/dendextend#32]
Hi,

I tried to use the function as.ggdend(), but an error is generated when type = "triangle".

Please, find below a reproducible R code:

```r
library(dendextend)
USArrests %>% scale %>% dist %>%
 hclust %>% as.dendrogram %>%
as.ggdend(type = "triangle")
```

I have got the following error:

**_Error in `$<-.data.frame`(`*tmp*`, "pch", value = c(NA, NA, NA, NA, NA,  : 
  replacement has 99 rows, data has 50_**

<pre>
Session info ----------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.4 (2016-03-10)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.99.491)          
 language (EN)                        
 collate  fr_FR.UTF-8                 
 tz       Europe/Paris                
 date     2016-11-08                  

Packages --------------------------------------------------------------------------------------------------------------------
 package      * version    date       source                         
 assertthat     0.1        2013-12-06 CRAN (R 3.2.0)                 
 class          7.3-14     2015-08-30 CRAN (R 3.2.4)                 
 cluster        2.0.3      2015-07-21 CRAN (R 3.2.4)                 
 colorspace     1.2-7      2016-10-11 CRAN (R 3.2.5)                 
 dendextend   * 1.3.0      2016-08-27 CRAN (R 3.2.5)                 
 DEoptimR       1.0-6      2016-07-06 CRAN (R 3.2.5)                 
 dichromat      2.0-0      2013-01-24 CRAN (R 3.2.0)                 
 digest         0.6.10     2016-08-02 CRAN (R 3.2.5)                 
 diptest        0.75-7     2015-06-08 CRAN (R 3.2.0)                 
 flexmix        2.3-13     2015-01-17 CRAN (R 3.2.0)                 
 fpc            2.1-10     2015-08-14 CRAN (R 3.2.0)                 
 ggplot2      * 2.1.0.9001 2016-10-18 Github (hadley/ggplot2@1709196)
 gtable         0.2.0      2016-02-26 CRAN (R 3.2.3)                 
 kernlab        0.9-25     2016-10-03 CRAN (R 3.2.5)                 
 labeling       0.3        2014-08-23 CRAN (R 3.2.0)                 
 lattice        0.20-33    2015-07-14 CRAN (R 3.2.4)                 
 lazyeval       0.2.0      2016-06-12 CRAN (R 3.2.5)                 
 magrittr       1.5        2014-11-22 CRAN (R 3.2.0)                 
 MASS           7.3-45     2015-11-10 CRAN (R 3.2.4)                 
 mclust         5.2        2016-03-31 CRAN (R 3.2.4)                 
 modeltools     0.2-21     2013-09-02 CRAN (R 3.2.0)                 
 munsell        0.4.3      2016-02-13 CRAN (R 3.2.3)                 
 mvtnorm        1.0-5      2016-02-02 CRAN (R 3.2.3)                 
 nnet           7.3-12     2016-02-02 CRAN (R 3.2.4)                 
 plyr           1.8.4      2016-06-08 CRAN (R 3.2.5)                 
 prabclus       2.2-6      2015-01-14 CRAN (R 3.2.0)                 
 RColorBrewer   1.1-2      2014-12-07 CRAN (R 3.2.0)                 
 Rcpp           0.12.7     2016-09-05 CRAN (R 3.2.5)                 
 reshape2       1.4.2      2016-10-22 CRAN (R 3.2.5)                 
 robustbase     0.92-6     2016-05-31 CRAN (R 3.2.5)                 
 scales         0.4.0.9003 2016-10-18 Github (hadley/scales@d58d83a) 
 stringi        1.1.2      2016-10-01 CRAN (R 3.2.5)                 
 stringr        1.1.0      2016-08-19 CRAN (R 3.2.5)                 
 tibble         1.2        2016-08-26 CRAN (R 3.2.5)                 
 trimcluster    0.1-2      2012-10-29 CRAN (R 3.2.0)                 
 whisker        0.3-2      2013-04-28 CRAN (R 3.2.0)        
</pre>

Best regards,
A.

**Comment by talgalili** [comment]
This feature is not currently available. At some point I might add it (we'll see...)

**Comment by kassambara** [comment]
Ok, thank you:-)!
