### ISSUE TITLE
tanglegram function: issue when using edge.lwd as well as common_subtrees_color_branches at the same time

### ISSUE THREAD

**Issue by kvpmulder** [talgalili/dendextend#33]
When trying to both add color to the subtrees as well as change branch width the tanglegram function gives an error. Find below both a function that reproduces the error as well as the error message. When using one or the other option separately the function works fine.

tanglegram(Phylo1,Phylo2, common_subtrees_color_branches=T, edge.lwd=4)

Error in value[is.na(values)] <- "black" : object 'value' not found
In addition: Warning message:
In branches_attr_by_clusters(dend2, dend2_clusters, values = dend1_leaves_colors[ss],  :
  There are NA's in the colors used by branches_attr_by_clusters. This probably means a bug somewhere. The color was replaced by 'black', but make sure your code does what you wanted it to...

**Comment by talgalili** [comment]
Hi @kvpmulder 
This issue should now be resolved.

With regards,
Tal
