### ISSUE TITLE
Variable per-branch lwd (regular dendogram)

### ISSUE THREAD

**Issue by peekxc** [talgalili/dendextend#34]
Similar title to the tanglegram issue, I was wondering if its possible to add support for variable length line widths for individual branches. An example of what I mean by this is shown on this page from [this library](http://nbviewer.jupyter.org/github/scikit-learn-contrib/hdbscan/blob/master/notebooks/How%20HDBSCAN%20Works.ipynb) in Python's scikit-learn module, in the "condensed tree" plot. The line widths steadily get smaller as they go down the branch, but the top horizontal 'split' lines remain the same line width.

**Comment by talgalili** [comment]
Thanks @peekxc 
I won't get to it this week, but will leave this request open and will add it eventually.
I have also been it touch with a college who will work on an hierarchical color scheme for the tree. I will probably add this as well.

With regards,
Tal

**Comment by talgalili** [comment]
Hello @peekxc 
I am happy to share with you the new functions added to dendextend:
`highlight_branches`
`highlight_branches_col`
`highlight_branches_lwd`
These can be used to highlight branches (via their color or line width, or both), based on their hight.

Here is a quick example:

```r
dat <- iris[1:20,-5]
hca <- hclust(dist(dat))
hca2 <- hclust(dist(dat), method = "single")
dend <- as.dendrogram(hca)
dend2 <- as.dendrogram(hca2)

par(mfrow = c(1,3))
dend %>% highlight_branches_col %>% plot(main = "Coloring branches")
dend %>% highlight_branches_lwd %>% plot(main = "Emphasizing line-width")
dend %>% highlight_branches %>% plot(main = "Emphasizing color\n and line-width")

```
Resulting in:

![image](https://cloud.githubusercontent.com/assets/976006/21466392/d1d4aca0-c9d2-11e6-85ed-95da10cae154.png)

These can also be accessed using the `set` function by using:

```r
par(mfrow = c(1,3))
dend %>% set("highlight_branches_col") %>% plot
dend %>% set("highlight_branches_lwd") %>% plot
dend %>% set("highlight_branches_col") %>% set("highlight_branches_lwd") %>% plot
```

I hope this solves your issue.

If you use dendextend in an academic paper, please consider citing it: http://bioinformatics.oxfordjournals.org/content/31/22/3718
(see also `citation("dendextend")` )

With regards,
Tal
