### ISSUE TITLE
Rstudio crashing when I call tanglegram

### ISSUE THREAD

**Issue by jrotieno** [talgalili/dendextend#36]
My Rstudio crushes whenever i call tanglegram as follows 

tanglegram(F,G)
 where F and G are my phylo trees of 50 tips each.
Note: I made the trees ultrametric using chronos before this command, otherwise it complained that they weren't ultrametric.

I decided to use the native R in Mac and while loading the dendextend library, I get the error below:
> library(dendextend)

 *** caught segfault ***
address 0x18, cause 'memory not mapped'

Traceback:
 1: dyn.load(file, DLLpath = DLLpath, ...)
 2: library.dynam(lib, package, package.lib)
 3: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
 4: asNamespace(ns)
 5: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
 6: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
 7: namespaceImport(ns, loadNamespace(i, c(lib.loc, .libPaths()),     versionCheck = vI[[i]]), from = package)
 8: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
 9: namespaceImport(ns, loadNamespace(i, c(lib.loc, .libPaths()),     versionCheck = vI[[i]]), from = package)
10: loadNamespace(package, lib.loc)
11: doTryCatch(return(expr), name, parentenv, handler)
12: tryCatchOne(expr, names, parentenv, handlers[[1L]])
13: tryCatchList(expr, classes, parentenv, handlers)
14: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
15: try({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps)})
16: library(dendextend)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspac

Any help?

**Comment by talgalili** [comment]
Could you send small self contained code for replicating this?

**Comment by jrotieno** [comment]
This is the code I am running (tree file attached)
[G_aln_IPnames_wanted copy.nwk.zip](https://github.com/talgalili/dendextend/files/767091/G_aln_IPnames_wanted.copy.nwk.zip)

library(ape)
library(dendextend)
library(distory)
library(dendextendRcpp)

#Reading in the same file twice just as an initial tester
G <- read.tree("G_aln_IPnames_wanted copy.nwk")
G_copy <- read.tree("G_aln_IPnames_wanted copy.nwk")

#To make the trees ultrametric
#This should make the trees ultrametric
G_ultra = chronos(G)
G_copy_ultra = chronos(G_copy)

#Finally to where it crashes
tanglegram(G_copy_ultra,G_ultra, sort = TRUE)

**Comment by jrotieno** [comment]
Was able to resolve this. Apparently it was an error with my R installation. I had two R installations; one with brew and the other using the .dmg file from CRAN and there seems to have been conflicts of sorts. Once I got rid of the brew installation, everything is perfect!

**Comment by talgalili** [comment]
Thanks for saying how you solved it :)

Cheers,
Tal
