### ISSUE TITLE
dend_diff changes plot settings

### ISSUE THREAD

**Issue by TomKellyGenetics** [talgalili/dendextend#37]
After running `dend_diff` my `par` is set for `mfrow=c(2,1)` when I run other plots afterwards. Is there a way to restrict the scope of this that it either:

1) Reverts to the original options for `par`
or
2) Defaults to `par(mfrow=c(1,1))` once it has completed

I suspect this may make it difficult to use in a script. The documentation is ambiguous as to what "side by side" means. Perhaps it would be beneficial to clarify that these are _separate_ plots, plotted horizontally.

**Comment by talgalili** [comment]
Thanks for the bug report @TomKellyGenetics (this is indeed a bug). It is now resolved in the most recent version on github.

Cheers,
Tal
