### ISSUE TITLE
prune.hclust breaks at as.hclust

### ISSUE THREAD

**Issue by JohnMCMa** [talgalili/dendextend#38]
````
library(dendextend)
hc <- hclust(dist(USArrests[1:5,]),"ave")
````
This gives out an error:
````
Error in as.hclust.dendrogram(x, ...) : 
  dendrogram entries must be 1,2,..,3 (in any order), to be coercible to "hclust"
````
While of course pruning leaves as dendrogram obviously work, coercing the resulting dendrogram to hclust don't work, either:
````
dendro <- as.dendrogram(hc)
dendro.pruned<-prune(dendro, c("Alaska","California"))
as.hclust(dendro.pruned)
Error in as.hclust.dendrogram(dendro.pruned) : 
  dendrogram entries must be 1,2,..,3 (in any order), to be coercible to "hclust"
````

Looking at the code for ````stats::as.hclust````, it seems the issue is the leaves' ID were not updated after pruning, like this:
````
> str(unclass(dendro.pruned))
List of 2
 $ : atomic [1:1] 4
  ..- attr(*, "members")= int 1
  ..- attr(*, "height")= num 0
  ..- attr(*, "label")= chr "Arkansas"
  ..- attr(*, "leaf")= logi TRUE
 $ :List of 2
  ..$ : atomic [1:1] 3
  .. ..- attr(*, "label")= chr "Arizona"
  .. ..- attr(*, "members")= int 1
  .. ..- attr(*, "height")= num 0
  .. ..- attr(*, "leaf")= logi TRUE
  ..$ : atomic [1:1] 1
  .. ..- attr(*, "label")= chr "Alabama"
  .. ..- attr(*, "members")= int 1
  .. ..- attr(*, "height")= num 0
  .. ..- attr(*, "leaf")= logi TRUE
  ..- attr(*, "members")= num 2
  ..- attr(*, "midpoint")= num 0.5
  ..- attr(*, "height")= num 52.6
 - attr(*, "members")= num 3
 - attr(*, "midpoint")= num 0.75
 - attr(*, "height")= num 82.6
````
Which makes some items in ````unlist(dendro.pruned)```` to be greater than ````nleaves(dendro.pruned)````, which in turn fails the first few lines of as.hclust.dendrogram:
````
as.hclust.dendrogram <- function(x, ...)
{
    stopifnot(is.list(x), length(x) == 2)
    n <- length(ord <- as.integer(unlist(x)))
    iOrd <- sort.list(ord)
    if(!identical(ord[iOrd], seq_len(n)))
	stop(gettextf(
	    "dendrogram entries must be 1,2,..,%d (in any order), to be coercible to \"hclust\"",
	    n), domain=NA)
````

To fix this, I think, would need to fix the leave indices such that they are within [1, `nleaves(dendro.pruned)`].

````
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dendextend_1.4.0

loaded via a namespace (and not attached):
 [1] flexmix_2.3-13    Rcpp_0.12.9       cluster_2.0.5     whisker_0.3-2     magrittr_1.5      fpc_2.1-10       
 [7] MASS_7.3-45       munsell_0.4.3     mclust_5.2.2      colorspace_1.3-2  lattice_0.20-34   plyr_1.8.4       
[13] prabclus_2.2-6    tools_3.3.2       nnet_7.3-12       grid_3.3.2        gtable_0.2.0      modeltools_0.2-21
[19] class_7.3-14      lazyeval_0.2.0    assertthat_0.1    tibble_1.2        gridExtra_2.2.1   kernlab_0.9-25   
[25] trimcluster_0.1-2 ggplot2_2.2.1     viridis_0.3.4     robustbase_0.92-7 DEoptimR_1.0-8    scales_0.4.1     
[31] diptest_0.75-7    stats4_3.3.2      mvtnorm_1.0-5   
````

**Comment by talgalili** [comment]
Thanks for the report. I won't get to it soon, but I hope to later on.

With regards,
Tal

**Comment by talgalili** [comment]
p.s.: you're welcome to submit a pull request here on github and I'd give it a look (best to do so while including relevant tests, if possible).

**Comment by JohnMCMa** [comment]
I have a fix in mind, but the resulting dendrogram, if more complex than USArrests, will still break at as.hclust (due to a different error) until R-3.4.0. It would, however, work in the simple example above. I'd have to try out whether R-3.4.0 works for my patch, though.

**Comment by JohnMCMa** [comment]
I put in #39 as my attempted fix to this problem, and the examples there involves a test of `all.equal`. However, I'm not sure whether just putting it as a post-processing step for `prune.hclust` is good enough; I think it may be beneficial for all flavors of `prune`; but running it after every instance of `prune.leaf` is excessive.

**Comment by talgalili** [comment]
I'm not going to go into this at the moment due to time constraints. I've accepted your patch. Please feel free to look at this further, and letting me know if you find a better way to handle it.

Cheers,
Tal

**Comment by talgalili** [comment]
ok, I think I've solved this issue in the latest commit. Please give it a look.

Best,
Tal
