### ISSUE TITLE
[Installation error] unable to load R code in package ‘flexmix’

### ISSUE THREAD

**Issue by hscleandro** [talgalili/dendextend#54]
I'm trying to submit a project using the dendextend R package to the [shinyio](https://www.shinyapps.io/) repository.

However, a error occurs for two libraries: flexmix and lme4. In house I fix this problem downloading the package, but the shinyio does not accept installation of manual or github packages .

Attached a image of this erro.

If someone has already gone through this thank you for the collaboration.

![erro_intallation_dendextend_shinyio](https://user-images.githubusercontent.com/4611796/29758333-ff67348a-8b88-11e7-92bd-18f41be3447a.png)

**Comment by talgalili** [comment]
Hi
How is flexmix related to dendextend?

**Comment by hscleandro** [comment]
Hello,

I believe these two packages are dependencies of the dendextend package, at least I had to install both on my machine in before to install the dendextend.

**Comment by talgalili** [comment]
I can't seem to see flexmix on https://cran.r-project.org/web/packages/dendextend/index.html
Please look at this further, I can't seem to reproduce this issue.

**Comment by hscleandro** [comment]
I created a video explaining the error reported in this topic, you can access on youtube:
https://www.youtube.com/watch?v=15ZH7uAHUmA&feature=youtu.be&a

Script code to reproduce the error you can get in github: https://github.com/hscleandro/teste_dendextend_shinyio

I hope my doubt is clear to you.

**Comment by talgalili** [comment]
Hi @hscleandro 
I apologize, but I don't see myself getting to solve this issue. Since this package is not used directly by dendextend, I'm not sure what to tell you. If you get to solve it yourself, please be so kind and post your solution here.

With regards,
Tal

**Comment by hscleandro** [comment]
The solution to this problem is to just update the R to latest version.

**Comment by talgalili** [comment]
Wonderful :)
