### ISSUE TITLE
add customization for upper_rect to rect.dendrogram

### ISSUE THREAD

**Issue by plantarum** [talgalili/dendextend#6]
When using rect.dendrogram to highlight a branch, the upper boundary lies overtop of the horizontal arm of the branch. This looks a bit awkward. It would be nice to be able to push the boundary up a little bit, so you could clearly see the horizontal branches inside the coloured box.

You already provide lower_rect to allow us to tidy up the bottom of the box. Could you add upper_rect for the other end?

Thanks for a great package!

**Comment by talgalili** [comment]
Just learned how to close ("fixes") an issue using the commits.
I wanted to thank you for the issue, I finally resolved it in dendextend 0.18.8.
It will probably take another month to get this version to CRAN, but it can be installed from github using:

```
devtools::install_github('talgalili/dendextend')
```

Thanks again,
Tal
