### ISSUE TITLE
Broken Dependency- viridis

### ISSUE THREAD

**Issue by SEpapoulis** [talgalili/dendextend#73]
dendextend fails to download due to a dependency 'viridis'. You first must install viridisLite in order to successfully install. Credit goes to @kim-carter for [the solution](https://github.com/rstudio/leaflet/issues/494)
Currently, to install dentextend, you must do the following:
`install.packages("viridisLite")  `  
`install.packages("viridis")`
`install.packages("dentextend")  `

**Comment by talgalili** [comment]
odd, I just tried to download it (after removing viridis and viridisLite) and it worked for me. Can you reproduce your issue? (and if so, what is your sessionInfo() ?)

**Comment by SEpapoulis** [comment]
I am sorry for the confusion, but I cannot seem to reproduce it now either. I removed dendextend, viridis and viridisLite and then reinstalled dendextend successfully (both dependencies were appropriately flagged and downloaded). The original error was thrown when trying to install viridis- when installing it through a namespace error for viridisLite.


Here is session info, not sure how helpful it will be now that I cannot reproduce the error:
```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.4 tools_3.4.4  
```

**Comment by talgalili** [comment]
Thanks.
ok, I'll close this for now and we'll see if someone else reports a similar issue.

Cheers,
T
