### ISSUE TITLE
Compiler compatibility - gfortran 7 and libgfortran.so.4

### ISSUE THREAD

**Issue by zwintrob** [talgalili/dendextend#74]
So, this is a problem that is beyond my ability to solve. When I updated my distro to Fedora 27 (from 25, though my understanding is 26 also used gfortran 7) dendextend failed to load because it relies libgfortran.so.3 (which is from gfortran 6? or possible 5?) which has been updated to libgfortran.so.4 as of gfortran 7, apparently with no backwards compatibility. Is it possible to update dendextend to find/compile with libgfortran.so.4?

**Comment by zwintrob** [comment]
So I did some more digging, it seems that the package mclust (which actually requires compilation) is causing the problem somewhere along the way. So I don't think this is a problem that you can necessarily solve. I will try reaching out to the mclust team.

**Comment by talgalili** [comment]
Hi @zwintrob 
I don't see mclust in the DESCRIPTION file (https://github.com/talgalili/dendextend/blob/master/DESCRIPTION)
why do you think is it loaded in relation to dendextend?

**Comment by zwintrob** [comment]
I thought the same thing based on the DESCRIPTION file, however, whenever I am trying to no reinstall dendextend it I get an error in the lazy loading referencing mclust. My best guess is that there is a chain to dependencies that eventually leads to mclust which does happen to require compiling. Here is the full output from when I try to install it:

Installing package into ‘/home/.../R/x86_64-redhat-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/dendextend_1.7.0.tar.gz'
Content type 'application/x-gzip' length 1747651 bytes (1.7 MB)
==================================================
downloaded 1.7 MB

* installing *source* package ‘dendextend’ ...
** package ‘dendextend’ successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** demo
** inst
** preparing package for lazy loading
**Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/.../R/x86_64-redhat-linux-gnu-library/3.4/mclust/libs/mclust.so':
  libgfortran.so.3: cannot open shared object file: No such file or directory**
ERROR: lazy loading failed for package ‘dendextend’
* removing ‘/home/.../R/x86_64-redhat-linux-gnu-library/3.4/dendextend’
Warning in install.packages :
  installation of package ‘dendextend’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpvuzFL3/downloaded_packages’

**Comment by zwintrob** [comment]
So, downloading and installing the missing compiler (I used the one from NASA at https://heasarc.gsfc.nasa.gov/lheasoft/linux.html) fixed the problem.

**Comment by talgalili** [comment]
Thanks for the update. Are you using install.packages? (I suspect it shouldn't try to go with suggest packages, only the depends and imports)
