### ISSUE TITLE
incomplete leaf label show for tanglegram tree comparing

### ISSUE THREAD

**Issue by MeiyuanJi** [talgalili/dendextend#82]
Hi, talgalili:
Thanks for this wonderful package. However, when I am comparing two trees with tanglegram() function, the display for the leaf label is uncomplete. Like this:
![default](https://user-images.githubusercontent.com/33933620/45505254-c7e2d100-b7be-11e8-86d1-22b8333e9a65.png)

How could I do to make the whole leaf name shown?
Thanks a lot.

**Comment by MeiyuanJi** [comment]
I am sorry, I guess I have find the solution. 
By setting margin_inner, it can be shown completely.

**Comment by talgalili** [comment]
Glad you figured it out, thanks for updating :)
