### ISSUE TITLE
Extracting edge information

### ISSUE THREAD

**Issue by Bann13** [talgalili/dendextend#83]
Hi,

Is there anyway to extract the au/pb number for the node that connects some specific samples?

https://stackoverflow.com/questions/52747567/how-to-extract-node-position-from-boot-hclust-object-
pvclust

**Comment by talgalili** [comment]
Hi @Bann13 
This would need to be programmed. If you get to do it, feel free to send a pull request to add it to dendextend.

Cheers,
T
