### ISSUE TITLE
Getting all member names under a particular node

### ISSUE THREAD

**Issue by Jayesh-Kumar-Sundaram** [talgalili/dendextend#98]
Do we have any attribute in the get_node_attr() function where we can get all the member names under a particular node?

**Comment by talgalili** [comment]
When you say names you mean the labels in the leaves or something else?

**Comment by Jayesh-Kumar-Sundaram** [comment]
Yes, labels in the leaves

**Comment by Jayesh-Kumar-Sundaram** [comment]
I wrote a small code to find all leave labels under a given node:

dend = hclust(as.dist(x), method = "average")

### Getting leaf labels under a given node ###
node_data = (dend$merge)

node_member_length = c()
member_list = list()

for(n in seq(from=1, to=dim(node_data)[1], by=1))
{
  members = c()
  members = append(members, node_data[n,1], after=length(members))
  members = append(members, node_data[n,2], after=length(members))
  i = 1
  while(i <= length(members))
  {
    if(as.numeric(members[i]) > 1)
    {
      members = append(members, node_data[members[i],1], after=length(members))
      members = append(members, node_data[members[i],2], after=length(members))
    }
    i = i + 1
  }
  members_index = which(members < 1)
  members = -1*(members[members_index])
  node_member_length = append(node_member_length, length(members), after=length(node_member_length))
  member_list = append(member_list, list(dend$labels[members]), after=length(member_list))
}

**Comment by talgalili** [comment]
Just to be sure - why do you need it?
I think labels would get it back if you give it the node. The question is
how to get to a node you're interested in. And that depends on your context.

**Comment by talgalili** [comment]
Thanks.
What's the use case?

**Comment by Jayesh-Kumar-Sundaram** [comment]
I constructed a tree based on gene expression data. I wanted to check whether a particular GO term is enriched in all sub-trees connected by a node. So, for all nodes i want to know all the genes under it to perform enrichment analysis.

**Comment by talgalili** [comment]
Just to verify, you closed the issue since you found a solution?
(if so, could you please write it also here?)

**Comment by Jayesh-Kumar-Sundaram** [comment]
I didn't find the solution using the "dendextend" package but I used the code I have written in my previous comment to get all member names under a particular node. If you wish to keep the issue open, we can re-open it. Thanks
